### ISSUE TITLE
Where the data is stored

### ISSUE THREAD

**Issue by ghost** [HolmesShuan/News-Spider#1]
After running the scripts, I still couldn't find where the data is stored. As is described in the readme.md  file, I created several folders in the ../data/netease etc and ran the corresponding code, but I couldn't find any data created in this folder. What's the problem? Thanks a lot.

**Comment by HolmesShuan** [comment]
Is there an exception? More details were required. THX.

**Comment by ghost** [comment]
The code is well written and there isn't any exception. There is still no data generated in the folder now. Should I create a xml file or any other type of files in the corresponding folder?

**Comment by HolmesShuan** [comment]
1. `#Download News-Spider-master.zip`
2. `unzip New-Spider-master.zip`
3.  `cd News-Spider-master`
4. `mkdir data`
5. `cd data`
6. `mkdir cankao`
7. `cd ../code`
8. `python3 cankaoxiaoxi_spider.py`
9. `#review ../data/cankao`
Try it again.

**Comment by ghost** [comment]
Great thanks for your generous help. I run the cankaoxiaoxi_spider.py just now, but there is a problem with exception.
![3](https://user-images.githubusercontent.com/34528540/34305395-eca7fa40-e778-11e7-8b06-00eb86c52fad.PNG)

![2](https://user-images.githubusercontent.com/34528540/34304997-2c5fe5b4-e777-11e7-9020-3d8c568830e2.PNG)
![2](https://user-images.githubusercontent.com/34528540/34305008-3ab60382-e777-11e7-94fd-23ab7fb0ecb5.PNG)
Perhaps I kown how to run the scripts, but it just doesn't work. As is shown in the  picture above, there isn't any data generated in data/netease folder. So it is with the other three scripts. The directory tree is as New-Spider-master/data/netease...

**Comment by HolmesShuan** [comment]
It seems that your network condition was not pretty well. `cankaoxiaoxi_spider.py` has been updated (STILL **BETA**). Also, since the web structure may change over time, we **can not** guarantee the usability of the code. For commercial use, we highly recommend you to turn to `goose` for long time support.  Thanks for your help.

**Comment by ghost** [comment]
Many thanks.
